# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardSlider' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardSlider
   pod 'ObjectMapper', '~> 3.4.2' #Manages Object maping
   pod 'Shuffle-iOS'
   pod "Koloda"
   pod 'iCarousel'
end
